# sync with https://github.com/fphammerle/docker-onion-service/blob/master/.github/dependabot.yml

version: 2

updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: friday

# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
