version: '2'

volumes:
  plain_data:
  encfs_password:

services:
  encfs:
    build: .
    image: fphammerle/reverse-encfs
    volumes:
    - plain_data:/plain/data:ro
    - encfs_password:/secret
    networks: []
    devices: [/dev/fuse]
    cap_add: [SYS_ADMIN]
    security_opt: ['apparmor:unconfined']

# https://docs.docker.com/compose/compose-file/compose-file-v2/
